### ISSUE TITLE
force POST in makeRequest

### ISSUE THREAD

**Issue by EistenGaming** [idietmoran/twitch-api#17]
Hi there

Is there a way of making `makeRequest()` use `POST `instead of `GET`? 

I am currently working on authentication functionality (OAuth2).

Cheers,
m

**Comment by Stateford** [comment]
@EistenGaming I could allow makeRequest to take some default arguments so we don't break any existing functionality, or we could make a new function `makePostRequest()`

The key here is to not break any existing API's.

Unfortunately when I made this library I was relatively new to programming, so working around what is already there is key.

**Comment by EistenGaming** [comment]
@Stateford I would suggest doing a makePostRequest() function. It's not breaking the API and also the signature / parameters of makeRequest() is not changed. What do you think?

**Comment by Stateford** [comment]
Sounds good to me. Would you like to make this change?

**Comment by EistenGaming** [comment]
@Stateford I am considering it :) I have seen that 'request.js' is deprecated (a dependency of this lib) and I am currently also looking at writing my own TwitchAPI based on the Axios lib (seems to be still quite active). What are your thoughts on this?

**Comment by Stateford** [comment]
@EistenGaming this project doesn't use request.js, it uses the built-in node.js http/https libraries.

**Comment by Stateford** [comment]
There is a way of making a post request already.

`request.post(url, params)`

closing as this is a non-issue.
