### ISSUE TITLE
Constructor passing undefined

### ISSUE THREAD

**Issue by Stateford** [idietmoran/twitch-api#5]
![image](https://user-images.githubusercontent.com/15315637/28246633-b0a53346-69ec-11e7-96b5-5785434ee49f.png)

using `console.log` on `process.env.TWITCH_ID` prints the correct id, but it's not being passed properly to our constructor during runtime / debug. Not sure if you are getting this issue on the latest build, but I'm trying to look into right now. I don't think it's a problem with `dotenv`

**Comment by Stateford** [comment]
even with hardcoding the ID I get the response:
```js
{ error: 'Bad Request',
  status: 400,
  message: 'The parameter "id" was malformed: the value must match the regular expression /^[0-9]+$/' }
```
but only for the `.getUser()` method it seems. Could you test this and see if you are experiencing this?

**Comment by Stateford** [comment]
Found the underlying issue [here](https://discuss.dev.twitch.tv/t/setting-client-id-with-http-get-angular-1/9301/3).

looks like using twitch APIv5 requires you to use the channels userid, not username.

Going to have to update this to v5 standards, as well as add a v3 function `makeRequestV3()` for handling the data.

**Comment by andyklimczak** [comment]
something related: https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api/#translating-from-user-names-to-user-ids
